### ISSUE TITLE
Cant set lore

### ISSUE THREAD

**Issue by Aman7123** [DSH105/EchoPet#198]
It seems that when you set up a lore in the config.yml it isn't red and added to the pets while looking at them in the pet selector menu.

```
slot-1:
  command: pet bat
  petType: BAT
  materialId: 383
  materialData: 65
  name: Bat Pet
  lore: '&9VIP+ &7Exclusive'
```

The lore isnt being red.
