### ISSUE TITLE
Config Overwritting

### ISSUE THREAD

**Issue by MeLlamoPeter** [DSH105/EchoPet#216]
Hi, im trying to set the pets for the server vips, but i dont want them to be flying or having a huge pet as a gigant.

ill paste some of the changings im doing in the config.yml Hope u can help me solve this, tnx for this amazing plugin

``` yml
 enderdragon:
    enable: false

blaze:
    enable: true
    tagVisible: false
    defaultName: Blaze de (user)
    interactMenu: false
    startFollowDistance: 8
    stopFollowDistance: 4
    teleportDistance: 40
    attack:
      canDamagePlayers: false
      lockRange: 10
      ticksBetweenAttacks: 20
      damage: 0.0
      loseHealth: false
      health: 20.0
    rideSpeed: 0.25
    jumpHeight: 0.6
    canFly: true
    allow:
      riders: false
      fire: true
    force:
      fire: false
```

Also, removing pets from the nether, cuz i have pvp enabled there

``` yml
worlds:
  spawn: true
  spawn_nether: false
  nether: false
  enableByDefault: true
```
