### ISSUE TITLE
Specific Pet Grants

### ISSUE THREAD

**Issue by Kainzo** [DSH105/EchoPet#543]
I've jumped ship from our private pet plugin onto EchoPets and I was curious if its possible to add this feature.

My store and reward system works in a way that each "pet type: meta" had its own permission. So players could find "Black Cat" and have access to /pet blackcat.   Now, this is still possible, but they are required to have the echopet.pet.type.ocelot and echopet.pet.type.ocelot.black -- in order to use it and even still, they are granted the ocelot (which is its own reward) AND they have to use it and change the type.

It's a bit restrictive for what I was using it for and this is a hard sale to my playerbase.

Thanks!

**Comment by CharlesVien** [comment]
You can always just fork it and edit it, since you already had a private pet plugin i'm assuming you have a developer.

**Comment by Kainzo** [comment]
yeah, not wanting to maintain a pet fork again.

**Comment by DSH105** [comment]
Not sure I quite understand the exact feature you're looking for here, so I'll list a few potential options below:
- Pets can be directly created with specific metadata using `/pet type;data` (e.g. `/pet ocelot;black`). Of course, this requires the user to have both `echopet.pet.<type>` and `echopet.pet.<type>.<data>`, so your reward plugin will need to grant both where applicable.
- If you're making use of the pet selection menu, you can provide a list of certain pet type-meta combinations for your players to choose from:
```yml
petSelector:
[...]
    menu:
        slots: 3
        title: Pets
        slot-1:
            command: pet ocelot;black
            petType: OCELOT
            materialId: #
            materialData: #
            name: Black Cat
            lore: []
        slot-2:
            command: pet ocelot;red
            petType: OCELOT
            materialId: #
            materialData: #
            name: Red Cat
            lore: []
        slot-3:
            command: pet wolf;green
            petType: WOLF
            materialId: #
            materialData: #
            name: Green Wolf
            lore: []
```

*This example configuration would display a menu with three items allowing selection of a black cat, red cat and green wolf.*

If I've missed something let me know :).
